PR5/Models/ErrorViewModel.cs
using System;

namespace PR5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PR5/Models/PR1Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PR5.Models
{
    public class PR1Model
    {
        public string Data { get; set; }

        public string ErrorValue { get; set; }
        public string Response { get; set; }
        public bool Calculated { get; set; }

    }
}

PR5/Models/PR2Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PR5.Models
{
    public class PR2Model
    {
        public string N { get; set; }
        public string Q { get; set; }

        public string ErrorValue { get; set; }
        public string Response { get; set; }
        public bool Calculated { get; set; }
    }
}

PR5/Models/UserProfileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PR5.Models
{
    public class UserProfileModel
    {
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

PR5/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Okta.AspNetCore;
using PR5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PR5.Controllers
{
    public class AccountController : Controller
    {

        public IActionResult SignIn()
        {
            if (!HttpContext.User.Identity.IsAuthenticated)
            {
                return Challenge(OktaDefaults.MvcAuthenticationScheme);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult OktaSignOut()
        {
            return new SignOutResult(new[]
            {
                OktaDefaults.MvcAuthenticationScheme,
                CookieAuthenticationDefaults.AuthenticationScheme
            },
            new AuthenticationProperties() { RedirectUri = "/Home/" });
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var phone = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "phone_number");
            return View(new UserProfileModel()
            {
                Email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email")?.Value.ToString() ?? "not specified",
                FirstName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "given_name")?.Value.ToString() ?? "not specified",
                LastName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "family_name")?.Value.ToString() ?? "not specified",
                UserName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "preferred_username" || x.Type == "name")?.Value.ToString() ?? "not specified",
                PhoneNumber = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "phone_number")?.Value.ToString() ?? "not specified"
            });
        }
    }
}

PR5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PR5.Models;

namespace PR5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PR5/Controllers/LabsController.cs
using LabsLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PR5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PR5.Controllers
{
    [Authorize]
    public class LabsController : Controller
    {
        public IActionResult PR1()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PR1(PR1Model Lab1Model)
        {
            try
            {
                Lab1Model.Response = new pr1()
                    .GetResult(Lab1Model.Data)
                    .ToString();
                Lab1Model.Calculated = true;
            }
            catch (Exception exception)
            {
                Lab1Model.ErrorValue = exception.Message;
            }
            return View(Lab1Model);
        }
        public IActionResult PR2()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PR2(PR2Model Lab2Model)
        {
            try
            {
                Lab2Model.Response = new Lab2()
                    .GetResult(Lab2Model.N,Lab2Model.Q )
                    .ToString();
                Lab2Model.Calculated = true;
            }
            catch (Exception exception)
            {
                Lab2Model.ErrorValue = exception.Message;
            }
            return View(Lab2Model);
        }
    }
}

PR5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PR5/Views/Labs/PR1.cshtml
@model PR5.Models.PR1Model 
@{
    ViewData["Title"] = "Lab-work 1";
}
<h1>@ViewData["Title"]</h1>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="PR1">
    <div class="form-group">
        <label for="pdata">Data</label>
        <input type="text" class="form-control" id="pdata" asp-for="Data">
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

@if (Model != null)
            {
                <div class="container mt-5">
                    @if (Model.Calculated)
                {
                    <div class="row">
                        <label for="presponse">Response</label>
                        <input type="text" id="presponse" value="@Model.Response">
                    </div>
                }
                    @if (!string.IsNullOrEmpty(Model.ErrorValue))
                    {
                        <div class="row">
                            <label for="perror"></label>
                            <input type="text" id="perror" value="@Model.ErrorValue" />
                        </div>
                    }
                </div>
            }

PR5/Views/Labs/PR2.cshtml
@model PR5.Models.PR2Model
@{
    ViewData["Title"] = "Lab-work 2";
}
<h1>@ViewData["Title"]</h1>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="PR2">
    <div class="form-group">
        <label for="pn">N</label>
        <input type="text" class="form-control" id="pn" asp-for="N">
    </div>
    <div class="form-group">
        <label for="pq">Q</label>
        <input type="text" class="form-control" id="pq" asp-for="Q">
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

@if (Model != null)
{
    <div class="container mt-5">
        @if (Model.Calculated)
        {
            <div class="row">
                <label for="presponse">Response</label>
                <input type="text" id="presponse" value="@Model.Response">
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.ErrorValue))
        {
            <div class="row">
                <label for="perror"></label>
                <input type="text" id="perror" value="@Model.ErrorValue" />
            </div>
        }
    </div>
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PR5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PR5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PR5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="PR1">Lab-work 1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="PR2">Lab-work 2</a>
                            </li>
}

                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if(User.Identity.IsAuthenticated)
            {
                <ul class="nav navbar-nav navbar-right">
                    <li><p class="navbar-text">Hello, @User.Identity.Name</p></li>
                    <li><a class="nav-link" asp-controller="Account" asp-action="Profile" id="profile-button">Profile</a></li>
                    <li>
                        <form class="form-inline" asp-controller="Account" asp-action="SignOut" method="post">
                            <button type="submit" class="nav-link btn btn-link text-dark" id="logout-button">Sign Out</button>
                        </form>
                    </li>
                </ul>
            }
            else
            {
                <ul class="nav nav-bar navbar-right">
                    <li><a asp-controller="Account" asp-action="SignIn" id="login-button">Sign in</a></li>
                </ul>
            }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PR5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>